### ISSUE TITLE
Compilation of Wireshark dissectors fails

### ISSUE THREAD

**Issue by ge0rg** [adafruit/Adafruit_BLESniffer_Python#4]
Hi,

I need to run the sniffer / Wireshark combination on Linux, but there are no instructions whatsoever to compile the Wireshark packet dissectors. Just trying to compile the files results in several error messages that look like you are targeting an old Wireshark API.

Please update the source for a current version of Wireshark and provide makefiles to compile it into a library (or at least instructions on how to integrate it into the Wireshark source). Thanks very much.

**Comment by microbuilder** [comment]
Unfortunately, Nordic won't provide the relevant Makefiles and build setup for this (we've tried to get the dissector makefiles and related files from them via a support request and the request was refused, though I'm not sure what they have to lose by enabling the use of their Python API in a wider context).

Perhaps filing a new request for the Linux and OS X dissector build system around the Python API might prod them to reconsider supporting the tool on other platforms if you're willing to spend a few minutes requesting it again via their My Pages support system or via the devzone.

Their answer for OS X was to redirect people to http://sourceforge.net/projects/nrfblesnifferosx/ but unfortunately the author of that tool doesn't provide any source for the project, and it isn't open source, so it's of little help to anyone wanting to keep things up to date.  The OS X tool also won't recognize anything based on an FTDI chip, and only looks for the USB VID/PID of the Segger J-Link firmware running on the Nordic dev kit, though it will install the dissector for Wireshark in the appropriate folder so that libpcap files captures via the Python API can be dissected inside Wireshark.

**Comment by ge0rg** [comment]
Thanks very much for the feedback. I've contacted them via "My Page", let's see how it turns out.

In the meantime, I tried to compile whatever they provided with Wireshark 1.12, looks like the required API changes are rather minimal. But so far I failed to create a .so that would be accepted by Wireshark as a plugin. Looks like I botched the metadata somehow.

**Comment by ladyada** [comment]
closing because we cant do anything about it!

**Comment by eknoes** [comment]
Since [Wireshark 2.4.0](https://www.wireshark.org/docs/relnotes/wireshark-2.4.0.html) the Nordic BLE is supported and included in wireshark!
